### ISSUE TITLE
ModuleNotFound / Test CLI in recipe?

### ISSUE THREAD

**Issue by kyleabeauchamp** [conda-forge/tensorboard-feedstock#1] opened 2017-12-09 21:26 UTC
I noticed that the recipe only tests the import of `tensorboard`, but in practice many users will be running the executable (`tensorboard` or `python -m tensorboard.main`).  We may want to test one or both of these in the recipe tests, possibly something like `tensorboard --help`.

On my install (py36 + tensorflow 1.4 + tb 0.4), I'm hitting an exception when running `tensorboard` at the CLI:

```
tensorboard
    import tensorflow.tensorboard.tensorboard
ModuleNotFoundError: No module named 'tensorflow.tensorboard'
```

I presume this may be due to the tensorboard 0.4 being in a RC state and the various packaging woes described in the recipe comments, but IMHO adding the CLI test will help keep things working.

**Comment by sdvillal** [comment] 2017-12-10 06:45
Oops, that should happen. 

We have a small chicken and egg problem here. Early when creating the recipe, [it was decided](https://github.com/conda-forge/staged-recipes/pull/3866) to follow the pip packages (broken) convention of inverting the dependencies; that is, to make tensorflow depend on tensorboard and not the other way round. On top of that, at least until now the tensorflow and tensorboard versions need to be well paired, practically meaning that we need to use the TB 0.4 series when using TF 1.4.

Bottom line is: we cannot test the CLI unless we have a tensorflow package with a correct version, and we cannot have a tensorflow package unless we have a tensorboard package. I will workaroud this here somehow and try to fix the problem, but in the future we need to decide how to proceed when upgrading TB+TF - create an initial TF package that does not depend on TB for testing, or installing TF from pip when testing the TB package or putting these tests on the TF package and synchronize well the release of both packages...

**Comment by sdvillal** [comment] 2017-12-10 08:18
The problem is in the tensorflow package. See: https://github.com/conda-forge/tensorflow-feedstock/pull/47. I'm adding a tensorboard CLI test there and hopefully it will be merged soon.

**Closed by sdvillal** 2017-12-10 08:18 UTC
Labels: bug
